name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "sh -c 'npx prisma migrate deploy && npx react-router dev --host 127.0.0.1 --port ${PORT:-3000} --strictPort'"
